/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author MiguelCastellanos
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        btnsae = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btncortesae = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btncortecajas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnventakits = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnfaltante = new javax.swing.JMenuItem();
        btncorteaspelcaja = new javax.swing.JMenu();
        btncortecaja = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnboucher = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 152, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 18, 152));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(200, 30));

        btnsae.setForeground(new java.awt.Color(255, 255, 255));
        btnsae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ASPEL-ICONO-VERT_SAE(2).png"))); // NOI18N
        btnsae.setText("  SAE   ");
        btnsae.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsae.setDelay(500);
        btnsae.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsae.add(jSeparator1);

        btncortesae.setText("     CaratulaCorte");
        btnsae.add(btncortesae);
        btnsae.add(jSeparator2);

        btncortecajas.setText("     CorteCajas");
        btnsae.add(btncortecajas);
        btnsae.add(jSeparator3);

        btnventakits.setText("     VentasKits");
        btnsae.add(btnventakits);
        btnsae.add(jSeparator4);

        btnfaltante.setText("     Faltante");
        btnsae.add(btnfaltante);

        jMenuBar2.add(btnsae);

        btncorteaspelcaja.setForeground(new java.awt.Color(255, 255, 255));
        btncorteaspelcaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-removebg-preview(1).png"))); // NOI18N
        btncorteaspelcaja.setText("   CAJA   ");
        btncorteaspelcaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncorteaspelcaja.setDelay(500);
        btncorteaspelcaja.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        btncortecaja.setText("       Corte       ");
        btncorteaspelcaja.add(btncortecaja);

        jMenuBar2.add(btncorteaspelcaja);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-electronica.png"))); // NOI18N
        jMenu1.setText("   BOUCHER");

        btnboucher.setText("       Bocher       ");
        jMenu1.add(btnboucher);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem btnboucher;
    public javax.swing.JMenu btncorteaspelcaja;
    public javax.swing.JMenuItem btncortecaja;
    public javax.swing.JMenuItem btncortecajas;
    public javax.swing.JMenuItem btncortesae;
    public javax.swing.JMenuItem btnfaltante;
    public javax.swing.JMenu btnsae;
    public javax.swing.JMenuItem btnventakits;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
